name: "Build and Deploy"

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

env:
  ARTIFACT: "webHelpDHUB2-all.zip"
  DOCKER_VERSION: "243.21565"
  INSTANCE: "Writerside/dhub"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Calculate latest Dungeon Hub API version
        run: kotlin .github/set-version.main.kts

      - uses: JetBrains/writerside-github-action@v4

        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version:  ${{ env.DOCKER_VERSION }}

      - uses: actions/upload-artifact@v4

        with:
          name: docs

          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json

          retention-days: 7

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4

        with:
          name: docs
          path: artifacts

      - uses: JetBrains/writerside-checker-action@v1

        with:
          instance: ${{ env.INSTANCE }}

  deploy:
    # Requires the build job results
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Switch branch

        run: |
          git checkout --orphan deployment

      - uses: actions/download-artifact@v4

        with:
          name: docs

      - uses: montudor/action-zip@v1

        with:
          args: unzip -qq ${{ env.ARTIFACT }} -d docs

      - name: Copy files, commit and push

        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions-user@users.noreply.github.com"

          cp -r docs/* .

          sudo rm -rf docs Writerside .github .idea .editorconfig .gitignore Dockerfile README.md

          git add .
          git commit -am "Automatic deployment"
          git push --force origin deployment
